scan:
  target_domains:
    - example.com
    - test.com
    - google.com
    - facebook.com
    - twitter.com
    - instagram.com
    - youtube.com
    - linkedin.com
    - github.com  

notifications:
  telegram_token: ""
  email: ""

