scan:
  target_domains:
    - example.com
    - test.com

notifications:
  # IMPORTANT: Do NOT commit real tokens. These are placeholders.
  telegram_token: "${TELEGRAM_BOT_TOKEN}"
  telegram_chat_id: "${TELEGRAM_CHAT_ID}"
